### ISSUE TITLE
Detailed Readme

### ISSUE THREAD

**Issue by joffilyfe** [VSPPedro/djangoecommerce#1]
Looking this name I am really interested about what mean this repository. @VSPPedro can you give some information?

Do you thinking in write one e-commerce in Django?

**Comment by VSPPedro** [comment]
This is just a course that got my attention. 

If you want to know more: https://www.udemy.com/construa-um-e-commerce-com-python-3-e-django/learn/v4/overview

I'm just going to try.

About the readme, I'll do that later on. Thank you, @joffilyfe , for reminding me.
